kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-my-secret-text.txt: 'secret/creds/my-secret-text'
    vault.hashicorp.com/role: "argocd"
    vault.hashicorp.com/agent-inject-template-my-secret-text.txt: |
      {{`{{ with secret "secret/data/creds/my-secret-text" -}}
        sample-secret={{ .Data.data.my-secret-text}}
      {{- end }}`}}
    avp.kubernetes.io/path: "secret/data/creds/my-secret-text"
    avp.kubernetes.io/kv-version: "2"
type: Opaque
stringData:
  sample-secret: sample-secret
