kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/creds/my-secret-text"
    avp.kubernetes.io/kv-version: "2"
type: Opaque
stringData:
  sample-secret: <secret>
